version: '3.8'

services:
  db:
    image: postgres:10-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env_docker
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_volume:
