'use strict'

const { TransactionModel } = require('../../../app/models')
const { RulesServiceTranslator, TransactionTranslator } = require('../../../app/translators')

const GeneralHelper = require('./general.helper')
const { presroc: requestFixtures } = require('../fixtures/create_transaction')
const { presroc: chargeFixtures } = require('../fixtures/calculate_charge')

class TransactionHelper {
  /**
   * Create a transaction
   *
   * Note: this will only create the transaction record. If you need to create a transaction properly with matching
   * invoice and licence records use `CreateTransactionService`.
   *
   * @param {string} billRunId Id of an actual bill run. We have a foreign key constraint which forces this requirement
   * @param {object} [overrides] JSON object of values which will override those generated by the helper. The primary
   *  source for the default values are the 'simple' request and 'rules service' fixtures. When specifying your
   *  overrides use the database names, for example, `lineAttr1` not `licenceNumber`
   *
   * @returns {module:TransactionModel} The newly created instance of `TransactionModel`.
   */
  static addTransaction (billRunId, overrides = {}) {
    return TransactionModel.query()
      .insert({
        ...this._defaultSimpleTransaction(billRunId),
        ...this._defaultSimpleCharge(),
        ...this._defaultValues(),
        ...overrides
      })
      .returning('*')
  }

  static _defaultSimpleTransaction (billRunId) {
    return new TransactionTranslator({
      billRunId,
      ...requestFixtures.simple,
      regimeId: GeneralHelper.uuid4(),
      authorisedSystemId: GeneralHelper.uuid4()
    })
  }

  static _defaultSimpleCharge () {
    return new RulesServiceTranslator({
      ...chargeFixtures.simple.rulesService
    })
  }

  static _defaultValues () {
    return {
      invoiceId: GeneralHelper.uuid4(),
      licenceId: GeneralHelper.uuid4()
    }
  }
}

module.exports = TransactionHelper
